language: java
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
env:
    - PUSHY_SSL_PROVIDER=jdk
    - PUSHY_SSL_PROVIDER=native
matrix:
    include:
        - dist: trusty
          group: edge
          sudo: required
          jdk: oraclejdk9
          env: PUSHY_SSL_PROVIDER=jdk
        - dist: trusty
          group: edge
          sudo: required
          jdk: oraclejdk9
          env: PUSHY_SSL_PROVIDER=native
    exclude:
        - jdk: oraclejdk7
          env: PUSHY_SSL_PROVIDER=jdk
        - jdk: openjdk7
          env: PUSHY_SSL_PROVIDER=jdk
